/**
 * VibeDesign-Harness Multi-Style & Multi-Theme Design System Engine
 * 100% Pure JavaScript (Zero Python Dependency)
 * Supports multiple design themes: Linear Dark, Stripe Clean, Vercel Mono, Airbnb Warm, Luxury Editorial, Cyberpunk.
 */

export const THEMES = {
    linear: {
        name: "Linear Precision Dark",
        bg: "#08090a",
        surface: "#121417",
        border: "#22252a",
        textMain: "#f7f8f8",
        textMuted: "#8a8f98",
        accent: "#5e6ad2",
        font: "Inter, system-ui, sans-serif",
        radius: "8px",
        mode: "dark"
    },
    stripe: {
        name: "Stripe Enterprise Clean",
        bg: "#f8fbfd",
        surface: "#ffffff",
        border: "#e6ebf1",
        textMain: "#0a2540",
        textMuted: "#425466",
        accent: "#635bff",
        font: "Inter, -apple-system, sans-serif",
        radius: "6px",
        mode: "light"
    },
    vercel: {
        name: "Vercel Minimalist Monochrome",
        bg: "#000000",
        surface: "#0a0a0a",
        border: "#333333",
        textMain: "#ffffff",
        textMuted: "#888888",
        accent: "#0070f3",
        font: "Geist, Geist Mono, monospace",
        radius: "6px",
        mode: "dark"
    },
    airbnb: {
        name: "Airbnb Warm Soft",
        bg: "#ffffff",
        surface: "#f7f7f7",
        border: "#dddddd",
        textMain: "#222222",
        textMuted: "#717171",
        accent: "#ff385c",
        font: "Circular, -apple-system, sans-serif",
        radius: "12px",
        mode: "light"
    },
    luxury_gold: {
        name: "Luxury Dark Emerald & Gold",
        bg: "#051610",
        surface: "#0a231b",
        border: "#184335",
        textMain: "#f4ede4",
        textMuted: "#a2b4ad",
        accent: "#d4af37",
        font: "Plus Jakarta Sans, Oswald, serif",
        radius: "10px",
        mode: "dark"
    },
    cyberpunk: {
        name: "Cyberpunk Neon Grid",
        bg: "#090a0f",
        surface: "#111422",
        border: "#252b45",
        textMain: "#00f0ff",
        textMuted: "#6f7a9f",
        accent: "#ff0055",
        font: "JetBrains Mono, monospace",
        radius: "4px",
        mode: "dark"
    }
};

/**
 * Generate comprehensive DESIGN.md token specification
 * @param {string} brandName Brand name or theme key
 * @param {string} customAccent Optional override for primary accent color
 * @param {string} themeOverride Force 'dark' or 'light'
 */
export function generateDesignMD(brandName = 'Linear', customAccent = null, themeOverride = null) {
    const key = brandName.toLowerCase().replace(/[^a-z0-9_]/g, '_');
    const baseTheme = THEMES[key] || THEMES.linear;
    
    const themeMode = themeOverride || baseTheme.mode;
    const accent = customAccent || baseTheme.accent;

    return `# DESIGN.md — ${brandName} Design Tokens & System Standards

> **Auto-generated by VibeDesign-Harness (Multi-Theme Engine)**  
> Theme: **${baseTheme.name}** | Mode: **${themeMode.toUpperCase()}**

---

## 1. 🎨 Color Hierarchy & Surface Tokens
- **Canvas Background:** \`${baseTheme.bg}\` (Deep foundation, zero washed-out gray)
- **Component Surface:** \`${baseTheme.surface}\` (Cards, dialogs, drawers)
- **Structural Border:** \`${baseTheme.border}\` (1px crisp boundary)
- **Primary Accent:** \`${accent}\` (Buttons, focus-visible rings, key metrics)
- **Text Main:** \`${baseTheme.textMain}\` (Headings, active copy, high contrast)
- **Text Muted:** \`${baseTheme.textMuted}\` (Captions, secondary labels)

---

## 2. ✍️ Typography Scale & Font Stack
- **Font Family:** \`${baseTheme.font}\`
- **Display Hero:** 48px / Line Height 1.1 / Font Weight 700 / Tracking -0.03em
- **H1 Section:** 32px / Line Height 1.2 / Font Weight 600 / Tracking -0.02em
- **H2 Card Title:** 20px / Line Height 1.3 / Font Weight 600
- **Body Regular:** 14px / Line Height 1.5 / Font Weight 400
- **Caption / Metric:** 12px / Line Height 1.4 / Font Weight 500

---

## 3. 🧩 Component Layout & Interaction Rules
- **Border Radius:** \`${baseTheme.radius}\` base, pills \`9999px\` for badges.
- **Button Standards:** Padding \`10px 18px\`, subtle 1px border highlight, \`focus-visible:ring-2\` with accent token. Never unstyled.
- **Card Standards:** 1px solid border \`${baseTheme.border}\`, background \`${baseTheme.surface}\`, soft ambient shadow only.
- **Transition:** CSS \`transition: all 150ms cubic-bezier(0.4, 0, 0.2, 1)\`.
`;
}

export function listThemes() {
    return Object.keys(THEMES).map(k => ({
        key: k,
        name: THEMES[k].name,
        mode: THEMES[k].mode,
        accent: THEMES[k].accent
    }));
}

export default {
    THEMES,
    generateDesignMD,
    listThemes
};
